name: Push component to https://components.espressif.com
# on: [push, pull_request]
on:
  push:
    tags:
      - v*
jobs:
  upload_components:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "esp-idf-cxx"
          version: ${{ github.ref_name }}
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}